spring:
  application:
    name: eureka-server-ha
server:
  port: 8762
eureka:
  datacenter: my-datacenter
  environment: test-environment
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka