spring:
  application:
    name: simple-web-service
#  cloud:
#    service-registry:
#      auto-registration:
#        enabled: true
server:
  port: 8000
logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    # true则将自己的ip注册到Eureka Server，false则将操作系统的hostname注册带Eureka Server
    prefer-ip-address: true
  client:
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://user:password123@localhost:8761/eureka/