spring:
  application:
    name: eureka-server-auth
  security:
    user:
      name: user
      password: password123
server:
  port: 8761
eureka:
  datacenter: my-datacenter
  environment: test-environment
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka